<?php
// install.php — One-time setup wizard. Delete after installation.
session_start();
define('EMS_INSTALL', true);

$base = __DIR__;
$installed_flag = $base . '/config/.installed';

if (file_exists($installed_flag)) {
    header('Location: index.php');
    exit;
}

$errors  = [];
$success = false;
$step    = isset($_POST['step']) ? (int)$_POST['step'] : 1;

// ── STEP 3: Process installation ────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 3) {
    $db_host   = trim($_POST['db_host'] ?? 'localhost');
    $db_name   = trim($_POST['db_name'] ?? '');
    $db_user   = trim($_POST['db_user'] ?? '');
    $db_pass   = $_POST['db_pass'] ?? '';
    $db_port   = trim($_POST['db_port'] ?? '3306');
    $sch_name  = trim($_POST['school_name'] ?? '');
    $sch_addr  = trim($_POST['school_address'] ?? '');
    $sch_phone = trim($_POST['school_phone'] ?? '');
    $sch_email = trim($_POST['school_email'] ?? '');
    $sch_type  = trim($_POST['school_type'] ?? 'school');
    $sch_board = trim($_POST['academic_board'] ?? 'DEB');
    $adm_user  = trim($_POST['admin_username'] ?? 'admin');
    $adm_pass  = $_POST['admin_password'] ?? '';
    $adm_name  = trim($_POST['admin_name'] ?? 'System Administrator');
    $adm_email = trim($_POST['admin_email'] ?? '');

    if (!$db_name)  $errors[] = 'Database name is required.';
    if (!$db_user)  $errors[] = 'Database username is required.';
    if (!$sch_name) $errors[] = 'School name is required.';
    if (strlen($adm_pass) < 6) $errors[] = 'Admin password must be at least 6 characters.';
    if ($adm_pass !== ($_POST['admin_password2'] ?? '')) $errors[] = 'Passwords do not match.';

    if (empty($errors)) {
        try {
            $dsn = "mysql:host={$db_host};port={$db_port};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            // Create database
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `{$db_name}`");

            // ── Run full schema ─────────────────────────────────────────────
            $sql = get_schema_sql();
            foreach (explode('-- SPLIT --', $sql) as $stmt) {
                $stmt = trim($stmt);
                if ($stmt) $pdo->exec($stmt);
            }

            // ── Seed data ───────────────────────────────────────────────────
            seed_data($pdo, $sch_name, $sch_addr, $sch_phone, $sch_email, $sch_type, $sch_board, $adm_user, $adm_pass, $adm_name, $adm_email);

            // ── Write config/db.php ──────────────────────────────────────────
            $config_content = <<<PHP
<?php
// Auto-generated by EMS Installer. Do not edit manually.
define('DB_HOST', '{$db_host}');
define('DB_PORT', '{$db_port}');
define('DB_NAME', '{$db_name}');
define('DB_USER', '{$db_user}');
define('DB_PASS', '{$db_pass}');
PHP;
            file_put_contents($base . '/config/db.php', $config_content);
            file_put_contents($installed_flag, date('Y-m-d H:i:s') . "\n");

            $success = true;
        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = 'Error: ' . $e->getMessage();
        }
    }
}

// ── Schema SQL ───────────────────────────────────────────────────────────────
// Tables are ordered so that every referenced table exists before the FK is declared.
// All patch columns (run_type, bonus_amount, etc.) are included in CREATE TABLE —
// no ALTER TABLE statements are needed for a fresh install.
function get_schema_sql(): string {
    return <<<'SQL'
-- PHASE 1: CORE SYSTEM
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    avatar VARCHAR(255) DEFAULT NULL,
    status ENUM('active','suspended','archived') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL,
    role_slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS user_roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_role (user_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    permission_key VARCHAR(100) UNIQUE NOT NULL,
    module VARCHAR(50) NOT NULL,
    label VARCHAR(150),
    description VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS role_permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    UNIQUE KEY unique_role_perm (role_id, permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS system_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    meta_key VARCHAR(100) UNIQUE NOT NULL,
    meta_value TEXT NOT NULL,
    meta_group VARCHAR(50) DEFAULT 'general',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS activity_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    action VARCHAR(100) NOT NULL,
    module VARCHAR(50),
    record_id INT DEFAULT NULL,
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_log_module (module, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 2: ACADEMIC
CREATE TABLE IF NOT EXISTS academic_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_name VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current TINYINT(1) DEFAULT 0,
    status ENUM('active','completed','upcoming') DEFAULT 'upcoming',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS classes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_name VARCHAR(100) NOT NULL,
    class_numeric INT DEFAULT NULL,
    class_level ENUM('playgroup','primary','secondary','higher_secondary','other') DEFAULT 'primary',
    display_order INT DEFAULT 0,
    status TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS sections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    section_name VARCHAR(50) NOT NULL,
    shift ENUM('morning','day','evening') DEFAULT 'day',
    capacity INT DEFAULT 40,
    class_teacher_id INT DEFAULT NULL,
    class_teacher_first_period_days VARCHAR(255) DEFAULT NULL,
    status TINYINT(1) DEFAULT 1,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (class_teacher_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS groups_stream (
    id INT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(100) NOT NULL,
    group_code VARCHAR(20) UNIQUE NOT NULL,
    applicable_from_class_level ENUM('secondary','higher_secondary','both') DEFAULT 'both'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS class_groups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    group_id INT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups_stream(id) ON DELETE CASCADE,
    UNIQUE KEY unique_class_group (class_id, group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS rooms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_name VARCHAR(100) NOT NULL,
    room_number VARCHAR(20),
    floor INT DEFAULT 1,
    capacity INT DEFAULT 30,
    room_type ENUM('classroom','lab','office','exam_hall','library','other') DEFAULT 'classroom',
    status TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject_name VARCHAR(150) NOT NULL,
    subject_code VARCHAR(30) UNIQUE,
    subject_type ENUM('core','religious','optional','4th_subject','practical') DEFAULT 'core',
    is_group_subject TINYINT(1) DEFAULT 0,
    is_religious_alt TINYINT(1) DEFAULT 0,
    can_be_4th TINYINT(1) DEFAULT 0,
    has_practical TINYINT(1) DEFAULT 0,
    has_mcq TINYINT(1) DEFAULT 0,
    status TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS class_subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    session_id INT NOT NULL,
    subject_id INT NOT NULL,
    group_id INT DEFAULT NULL,
    full_marks_written INT DEFAULT 0,
    full_marks_mcq INT DEFAULT 0,
    full_marks_practical INT DEFAULT 0,
    pass_marks_written INT DEFAULT 0,
    pass_marks_mcq INT DEFAULT 0,
    pass_marks_practical INT DEFAULT 0,
    periods_per_week INT DEFAULT 1,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    UNIQUE KEY unique_class_subject (class_id, session_id, subject_id, group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS routine_slots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    subject_id INT NOT NULL,
    teacher_id INT DEFAULT NULL,
    room_id INT DEFAULT NULL,
    day_of_week ENUM('Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday') NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_substitute TINYINT(1) DEFAULT 0,
    substitute_date DATE DEFAULT NULL,
    status TINYINT(1) DEFAULT 1,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (section_id) REFERENCES sections(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 3: STUDENTS
CREATE TABLE IF NOT EXISTS student_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    student_id_no VARCHAR(50) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    dob DATE,
    gender ENUM('male','female','other'),
    religion VARCHAR(30),
    blood_group VARCHAR(5),
    photo VARCHAR(255),
    father_name VARCHAR(150),
    mother_name VARCHAR(150),
    guardian_name VARCHAR(150),
    guardian_phone VARCHAR(20),
    guardian_relation VARCHAR(50) DEFAULT 'Father',
    address_present TEXT,
    address_permanent TEXT,
    birth_certificate_no VARCHAR(50),
    nid_no VARCHAR(20),
    previous_school VARCHAR(200),
    admission_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS student_enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    group_id INT DEFAULT NULL,
    roll_number INT NOT NULL,
    status ENUM('active','transferred','opt_out','graduated','suspended') DEFAULT 'active',
    join_month INT DEFAULT NULL COMMENT 'Month student joined mid-session (1-12, NULL = from session start)',
    join_year INT DEFAULT NULL  COMMENT 'Year of mid-session join',
    left_date DATE DEFAULT NULL COMMENT 'Date student left/transferred in this session',
    left_reason VARCHAR(255) DEFAULT NULL,
    status_changed_by INT DEFAULT NULL,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (section_id) REFERENCES sections(id),
    FOREIGN KEY (status_changed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_enrollment (session_id, class_id, section_id, roll_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS special_batches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_name VARCHAR(150) NOT NULL,
    description TEXT,
    batch_type ENUM('scholarship','talent_pool','remedial','model_test','coaching','other') DEFAULT 'other',
    session_id INT NOT NULL,
    teacher_id INT DEFAULT NULL,
    start_date DATE,
    end_date DATE,
    status TINYINT(1) DEFAULT 1,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS batch_enrollments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_id INT NOT NULL,
    student_id INT NOT NULL,
    joined_at DATE,
    status ENUM('active','left') DEFAULT 'active',
    FOREIGN KEY (batch_id) REFERENCES special_batches(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS student_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    doc_type VARCHAR(50),
    doc_name VARCHAR(255),
    file_path VARCHAR(500),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS tc_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    file_number VARCHAR(50) UNIQUE,
    issued_date DATE NOT NULL,
    reason TEXT,
    destination_school VARCHAR(200),
    approved_by INT DEFAULT NULL,
    status ENUM('pending','issued') DEFAULT 'pending',
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 4: EXAMS
CREATE TABLE IF NOT EXISTS exams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    exam_name VARCHAR(150) NOT NULL,
    exam_type ENUM('terminal','monthly','model_test','scholarship','annual','midterm','final','other') DEFAULT 'other',
    start_date DATE,
    end_date DATE,
    status ENUM('draft','scheduled','ongoing','results_published') DEFAULT 'draft',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS exam_class_map (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    class_id INT NOT NULL,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    UNIQUE KEY unique_exam_class (exam_id, class_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS exam_subject_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    class_id INT NOT NULL,
    subject_id INT NOT NULL,
    full_marks_written INT DEFAULT 0,
    full_marks_mcq INT DEFAULT 0,
    full_marks_practical INT DEFAULT 0,
    pass_marks_written INT DEFAULT 0,
    pass_marks_mcq INT DEFAULT 0,
    pass_marks_practical INT DEFAULT 0,
    exam_date DATE,
    exam_time TIME,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS exam_seats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    room_id INT NOT NULL,
    student_id INT NOT NULL,
    seat_number VARCHAR(10),
    row_no INT,
    col_no INT,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS exam_invigilators (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    room_id INT NOT NULL,
    teacher_id INT NOT NULL,
    duty_date DATE NOT NULL,
    duty_type ENUM('chief_invigilator','invigilator','assistant') DEFAULT 'invigilator',
    allowance_amount DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS marks_entry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    student_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    subject_id INT NOT NULL,
    marks_written DECIMAL(5,2) DEFAULT NULL,
    marks_mcq DECIMAL(5,2) DEFAULT NULL,
    marks_practical DECIMAL(5,2) DEFAULT NULL,
    is_absent TINYINT(1) DEFAULT 0,
    entered_by INT,
    entered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    UNIQUE KEY unique_marks (exam_id, student_id, subject_id),
    INDEX idx_marks_lookup (exam_id, class_id, section_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS question_vault (
    id INT AUTO_INCREMENT PRIMARY KEY,
    exam_id INT NOT NULL,
    class_id INT NOT NULL,
    subject_id INT NOT NULL,
    submitted_by INT NOT NULL,
    file_path VARCHAR(500),
    notes TEXT,
    status ENUM('draft','pending_review','approved','rejected') DEFAULT 'draft',
    reviewed_by INT DEFAULT NULL,
    reviewed_at TIMESTAMP NULL,
    FOREIGN KEY (exam_id) REFERENCES exams(id),
    FOREIGN KEY (submitted_by) REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 5: HR
CREATE TABLE IF NOT EXISTS staff_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    employee_id VARCHAR(50) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    designation VARCHAR(100),
    department VARCHAR(100),
    dob DATE,
    gender ENUM('male','female','other'),
    religion VARCHAR(30),
    blood_group VARCHAR(5),
    photo VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(100),
    address TEXT,
    nid_no VARCHAR(20),
    joining_date DATE,
    contract_type ENUM('permanent','contractual','part_time','guest_lecturer') DEFAULT 'permanent',
    salary_type ENUM('fixed','hourly','class_wise','attendance_based') DEFAULT 'fixed',
    base_salary DECIMAL(10,2) DEFAULT 0.00,
    bank_account VARCHAR(50),
    bank_name VARCHAR(100),
    tin_no VARCHAR(30),
    max_classes_per_day INT DEFAULT 6,
    max_classes_per_week INT DEFAULT 30,
    status ENUM('active','resigned','terminated','retired') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS leave_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    leave_name VARCHAR(100) NOT NULL,
    annual_quota INT DEFAULT 0,
    is_paid TINYINT(1) DEFAULT 1,
    applicable_to ENUM('all','teacher','staff') DEFAULT 'all'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS leave_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id INT NOT NULL,
    leave_type_id INT NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    total_days INT NOT NULL,
    reason TEXT,
    status ENUM('pending','approved','rejected','cancelled') DEFAULT 'pending',
    approved_by INT DEFAULT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (staff_id) REFERENCES users(id),
    FOREIGN KEY (leave_type_id) REFERENCES leave_types(id),
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS staff_attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id INT NOT NULL,
    attendance_date DATE NOT NULL,
    status ENUM('present','absent','late','half_day','on_leave') DEFAULT 'present',
    in_time TIME DEFAULT NULL,
    out_time TIME DEFAULT NULL,
    marked_by INT DEFAULT NULL,
    FOREIGN KEY (staff_id) REFERENCES users(id),
    UNIQUE KEY unique_staff_att (staff_id, attendance_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS student_attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    attendance_date DATE NOT NULL,
    status ENUM('present','absent','late','excused') DEFAULT 'present',
    marked_by INT DEFAULT NULL,
    FOREIGN KEY (student_id) REFERENCES users(id),
    UNIQUE KEY unique_student_att (student_id, attendance_date),
    INDEX idx_att_class (session_id, class_id, section_id, attendance_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS payroll_runs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    month INT NOT NULL,
    year INT NOT NULL,
    status ENUM('draft','finalized','paid') DEFAULT 'draft',
    run_type ENUM('regular','custom') DEFAULT 'regular',
    description VARCHAR(255) DEFAULT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY unique_payroll_period (session_id, month, year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS payroll_lines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    payroll_run_id INT NOT NULL,
    staff_id INT NOT NULL,
    base_salary DECIMAL(10,2) DEFAULT 0.00,
    bonus_amount DECIMAL(10,2) DEFAULT 0.00,
    bonus_desc VARCHAR(150) DEFAULT NULL,
    exam_duty_allowance DECIMAL(10,2) DEFAULT 0.00,
    extra_class_allowance DECIMAL(10,2) DEFAULT 0.00,
    other_additions DECIMAL(10,2) DEFAULT 0.00,
    tax_deduction DECIMAL(10,2) DEFAULT 0.00,
    provident_fund DECIMAL(10,2) DEFAULT 0.00,
    advance_deduction DECIMAL(10,2) DEFAULT 0.00,
    fine_deduction DECIMAL(10,2) DEFAULT 0.00,
    absence_deduction DECIMAL(10,2) DEFAULT 0.00,
    net_salary DECIMAL(10,2) DEFAULT 0.00,
    payment_status ENUM('unpaid','paid') DEFAULT 'unpaid',
    notes TEXT,
    FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs(id),
    FOREIGN KEY (staff_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS performance_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id INT NOT NULL,
    log_type ENUM('evaluation','disciplinary','commendation','warning') DEFAULT 'evaluation',
    description TEXT NOT NULL,
    action_taken TEXT,
    logged_by INT NOT NULL,
    log_date DATE NOT NULL,
    is_confidential TINYINT(1) DEFAULT 1,
    FOREIGN KEY (staff_id) REFERENCES users(id),
    FOREIGN KEY (logged_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 6: ACCOUNTS (must be created before fee_payments, incomes, expenses which FK reference it)
CREATE TABLE IF NOT EXISTS accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_name VARCHAR(100) NOT NULL,
    account_type ENUM('cash', 'bank', 'mobile_banking') NOT NULL,
    account_number VARCHAR(50) DEFAULT NULL,
    bank_name VARCHAR(100) DEFAULT NULL,
    current_balance DECIMAL(12,2) DEFAULT 0.00,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS account_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    transaction_type ENUM('deposit', 'withdrawal', 'transfer', 'adjustment') NOT NULL,
    description VARCHAR(255) NOT NULL,
    reference_table VARCHAR(50) DEFAULT NULL,
    reference_id INT DEFAULT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 7: FINANCE
CREATE TABLE IF NOT EXISTS fee_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    category_type ENUM('tuition','admission','session','transport','hostel','exam','library','sport','custom','fine') DEFAULT 'custom',
    description TEXT,
    status TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS fee_structures (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    fee_category_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    due_day INT DEFAULT 10,
    frequency ENUM('monthly','quarterly','yearly','once') DEFAULT 'monthly',
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (fee_category_id) REFERENCES fee_categories(id),
    UNIQUE KEY unique_fee_structure (session_id, class_id, fee_category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS fee_ledgers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    session_id INT NOT NULL,
    fee_category_id INT NOT NULL,
    amount_due DECIMAL(10,2) NOT NULL,
    amount_paid DECIMAL(10,2) DEFAULT 0.00,
    waiver_status ENUM('none','pending','approved') DEFAULT 'none',
    waiver_amount DECIMAL(10,2) DEFAULT 0.00,
    due_date DATE NOT NULL,
    month INT DEFAULT NULL,
    year INT DEFAULT NULL,
    status ENUM('unpaid','partial','paid') DEFAULT 'unpaid',
    notes TEXT DEFAULT NULL COMMENT 'Custom fee description for ad-hoc entries',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (fee_category_id) REFERENCES fee_categories(id),
    INDEX idx_fee_lookup (student_id, waiver_status, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS fee_payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ledger_id INT NOT NULL,
    student_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method ENUM('cash','bank','mobile_banking','cheque','online') DEFAULT 'cash',
    receipt_number VARCHAR(50) UNIQUE,
    collected_by INT,
    notes TEXT,
    account_id INT DEFAULT NULL,
    approval_status ENUM('approved','pending','void') DEFAULT 'approved',
    void_reason TEXT DEFAULT NULL,
    voided_by INT DEFAULT NULL,
    voided_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (ledger_id) REFERENCES fee_ledgers(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (collected_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    FOREIGN KEY (voided_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS waivers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    ledger_id INT NOT NULL,
    requested_amount DECIMAL(10,2) NOT NULL,
    waiver_reason TEXT NOT NULL,
    waiver_type ENUM('full','partial','session_bulk') DEFAULT 'partial',
    effective_from_month INT DEFAULT NULL,
    effective_from_year INT DEFAULT NULL,
    requested_by INT NOT NULL,
    request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_by INT DEFAULT NULL,
    review_date TIMESTAMP NULL,
    status ENUM('pending','approved','rejected','void') DEFAULT 'pending',
    voided_by INT DEFAULT NULL,
    void_reason TEXT DEFAULT NULL,
    voided_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (ledger_id) REFERENCES fee_ledgers(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (voided_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS income_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS incomes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    income_category_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    income_date DATE NOT NULL,
    description TEXT,
    received_by INT,
    account_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (income_category_id) REFERENCES income_categories(id),
    FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS expense_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    expense_category_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    expense_date DATE NOT NULL,
    description TEXT,
    vendor VARCHAR(200),
    invoice_no VARCHAR(100),
    approved_by INT DEFAULT NULL,
    status ENUM('pending','approved','rejected') DEFAULT 'approved',
    account_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (expense_category_id) REFERENCES expense_categories(id),
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 7: INVENTORY
CREATE TABLE IF NOT EXISTS asset_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_category_id INT NOT NULL,
    asset_name VARCHAR(200) NOT NULL,
    serial_number VARCHAR(100),
    purchase_date DATE,
    purchase_price DECIMAL(10,2) DEFAULT 0.00,
    vendor VARCHAR(200),
    warranty_until DATE,
    location_room_id INT DEFAULT NULL,
    status ENUM('available','assigned','maintenance','disposed') DEFAULT 'available',
    notes TEXT,
    FOREIGN KEY (asset_category_id) REFERENCES asset_categories(id),
    FOREIGN KEY (location_room_id) REFERENCES rooms(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS asset_assignments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT NOT NULL,
    assigned_to INT NOT NULL,
    assigned_by INT NOT NULL,
    assigned_date DATE NOT NULL,
    return_date DATE DEFAULT NULL,
    condition_out ENUM('excellent','good','fair','poor') DEFAULT 'good',
    condition_in ENUM('excellent','good','fair','poor','damaged') DEFAULT NULL,
    status ENUM('active','returned') DEFAULT 'active',
    notes TEXT,
    FOREIGN KEY (asset_id) REFERENCES assets(id),
    FOREIGN KEY (assigned_to) REFERENCES users(id),
    FOREIGN KEY (assigned_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS consumable_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS consumables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    consumable_category_id INT NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    item_code VARCHAR(50) UNIQUE,
    unit VARCHAR(30) DEFAULT 'piece',
    current_stock INT DEFAULT 0,
    min_threshold INT DEFAULT 10,
    unit_cost DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (consumable_category_id) REFERENCES consumable_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS consumable_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    consumable_id INT NOT NULL,
    transaction_type ENUM('purchase','issue','return','disposal','adjustment') DEFAULT 'purchase',
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) DEFAULT 0.00,
    total_price DECIMAL(10,2) DEFAULT 0.00,
    issued_to INT DEFAULT NULL,
    transaction_date DATE NOT NULL,
    notes TEXT,
    created_by INT,
    FOREIGN KEY (consumable_id) REFERENCES consumables(id),
    FOREIGN KEY (issued_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 8: ECA
CREATE TABLE IF NOT EXISTS clubs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    club_name VARCHAR(150) NOT NULL,
    club_type ENUM('academic','sports','cultural','debate','science','other') DEFAULT 'other',
    moderator_id INT DEFAULT NULL,
    description TEXT,
    founded_date DATE,
    status TINYINT(1) DEFAULT 1,
    FOREIGN KEY (moderator_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS club_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    club_id INT NOT NULL,
    student_id INT NOT NULL,
    role_in_club VARCHAR(50) DEFAULT 'member',
    joined_date DATE,
    status ENUM('active','left') DEFAULT 'active',
    FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    event_name VARCHAR(200) NOT NULL,
    event_type ENUM('annual_sports','cultural','study_tour','debate','seminar','other') DEFAULT 'other',
    club_id INT DEFAULT NULL,
    start_date DATE,
    end_date DATE,
    budget_allocated DECIMAL(10,2) DEFAULT 0.00,
    description TEXT,
    status ENUM('planning','ongoing','completed','cancelled') DEFAULT 'planning',
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS event_expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    expense_date DATE NOT NULL,
    approved_by INT DEFAULT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 9: COMMUNICATION & DOCUMENTS
CREATE TABLE IF NOT EXISTS sms_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(100) NOT NULL,
    template_body TEXT NOT NULL,
    trigger_type ENUM('attendance','fee_due','result','emergency','custom') DEFAULT 'custom',
    status TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS sms_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipient_phone VARCHAR(20) NOT NULL,
    recipient_id INT DEFAULT NULL,
    message TEXT NOT NULL,
    template_id INT DEFAULT NULL,
    sent_by INT DEFAULT NULL,
    status ENUM('pending','sent','failed') DEFAULT 'pending',
    gateway_response TEXT,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sent_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS document_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(100) NOT NULL,
    template_type ENUM('tc','character_certificate','testimonial','official_letter','custom') DEFAULT 'custom',
    template_body LONGTEXT NOT NULL,
    paper_size ENUM('A4','legal','letter') DEFAULT 'A4',
    status TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS document_issues (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_id INT NOT NULL,
    student_id INT DEFAULT NULL,
    staff_id INT DEFAULT NULL,
    issue_date DATE NOT NULL,
    serial_number VARCHAR(50) UNIQUE,
    issued_by INT NOT NULL,
    notes TEXT,
    FOREIGN KEY (template_id) REFERENCES document_templates(id),
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (issued_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS incidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    incident_type ENUM('student_discipline','staff_discipline','complaint','other') DEFAULT 'other',
    subject_id INT NOT NULL,
    description TEXT NOT NULL,
    action_taken TEXT,
    incident_date DATE NOT NULL,
    logged_by INT NOT NULL,
    status ENUM('open','resolved','dismissed') DEFAULT 'open',
    is_confidential TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_id) REFERENCES users(id),
    FOREIGN KEY (logged_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS holiday_calendar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT DEFAULT NULL,
    holiday_date DATE NOT NULL,
    holiday_name VARCHAR(200) NOT NULL,
    holiday_type ENUM('govt','institutional','weekend','custom') DEFAULT 'institutional',
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
CREATE TABLE IF NOT EXISTS alumni (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT DEFAULT NULL,
    full_name VARCHAR(150) NOT NULL,
    last_class_id INT DEFAULT NULL,
    pass_year INT,
    current_institution VARCHAR(200),
    current_profession VARCHAR(200),
    phone VARCHAR(20),
    email VARCHAR(100),
    photo VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (last_class_id) REFERENCES classes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 11: TEACHER SUBJECT EXPERTISE
CREATE TABLE IF NOT EXISTS teacher_subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_id INT NOT NULL,
    subject_id INT NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    UNIQUE KEY unique_teacher_subject (teacher_id, subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 11B: TEACHER CLASS TRACKING
CREATE TABLE IF NOT EXISTS teacher_class_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    subject_id INT NOT NULL,
    teacher_id INT NOT NULL,
    slot_id INT DEFAULT NULL,
    log_date DATE NOT NULL,
    status ENUM('conducted','missed') DEFAULT 'conducted',
    notes TEXT DEFAULT NULL,
    marked_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (section_id) REFERENCES sections(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id),
    FOREIGN KEY (marked_by) REFERENCES users(id),
    UNIQUE KEY unique_class_log (slot_id, log_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 12: STAFF LOANS
CREATE TABLE IF NOT EXISTS staff_loans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    staff_id INT NOT NULL,
    loan_amount DECIMAL(10,2) NOT NULL,
    interest_rate DECIMAL(5,2) DEFAULT 0.00,
    total_repayable DECIMAL(10,2) NOT NULL,
    monthly_installment DECIMAL(10,2) NOT NULL,
    amount_repaid DECIMAL(10,2) DEFAULT 0.00,
    disbursed_date DATE NOT NULL,
    status ENUM('active','paid','defaulted') DEFAULT 'active',
    transferred_to_loan_id INT DEFAULT NULL,
    transferred_to_user_id INT DEFAULT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (staff_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 11C: PAYMENT VOID AUDIT LOG
CREATE TABLE IF NOT EXISTS payment_void_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    entity_type ENUM('payment','waiver') NOT NULL,
    entity_id INT NOT NULL,
    action ENUM('void','approve','reject','restore','partial_approve','partial_reject') NOT NULL,
    old_status VARCHAR(50) DEFAULT NULL,
    new_status VARCHAR(50) DEFAULT NULL,
    amount_affected DECIMAL(10,2) DEFAULT 0.00,
    performed_by INT NOT NULL,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (performed_by) REFERENCES users(id),
    INDEX idx_pvl_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 12: CUSTOM PAYMENTS VOUCHER
CREATE TABLE IF NOT EXISTS custom_payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    payee_name VARCHAR(150) NOT NULL,
    payee_role ENUM('staff', 'management', 'vendor', 'other') DEFAULT 'other',
    user_id INT DEFAULT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    account_id INT NOT NULL,
    notes TEXT,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 13: NOTICE BOARD
CREATE TABLE IF NOT EXISTS notices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    audience ENUM('all','students','staff') DEFAULT 'all',
    created_by INT NOT NULL,
    publish_date DATE NOT NULL,
    is_broadcast TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 14A: ROUTINE CUSTOM DAYS
CREATE TABLE IF NOT EXISTS section_working_days (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT DEFAULT NULL,
    working_days VARCHAR(150) DEFAULT 'Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday',
    periods_start_time TIME DEFAULT '09:00:00',
    periods_end_time TIME DEFAULT '15:00:00',
    notes VARCHAR(255) DEFAULT NULL,
    updated_by INT DEFAULT NULL,
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY unique_section_days (session_id, class_id, section_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 14B: SESSION CLONE LOG
CREATE TABLE IF NOT EXISTS session_clone_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    from_session_id INT NOT NULL,
    to_session_id INT NOT NULL,
    cloned_by INT NOT NULL,
    cloned_items JSON DEFAULT NULL,
    notes VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (to_session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (cloned_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 14C: ROLL NUMBER CHANGE LOG
CREATE TABLE IF NOT EXISTS roll_change_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    session_id INT NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    old_roll INT NOT NULL,
    new_roll INT NOT NULL,
    changed_by INT NOT NULL,
    reason VARCHAR(255) DEFAULT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (session_id) REFERENCES academic_sessions(id),
    FOREIGN KEY (changed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
-- SPLIT --
-- PHASE 14: FEEDBACK & REPORTS
CREATE TABLE IF NOT EXISTS feedback_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reporter_role ENUM('student','staff','other') DEFAULT 'other',
    user_id INT DEFAULT NULL,
    feedback_type ENUM('suggestion','problem','asking','other') DEFAULT 'suggestion',
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    is_anonymous TINYINT(1) DEFAULT 0,
    status ENUM('submitted','reviewed','action_taken','archived') DEFAULT 'submitted',
    action_taken TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
SQL;
}

// ── Seed data ─────────────────────────────────────────────────────────────────
function seed_data(PDO $pdo, string $sch_name, string $sch_addr, string $sch_phone,
    string $sch_email, string $sch_type, string $sch_board,
    string $adm_user, string $adm_pass, string $adm_name, string $adm_email): void
{
    // Roles
    $roles = [
        ['Super Admin',          'super_admin',    'Full system access — all modules'],
        ['Principal',            'principal',      'Head of institution, read-all + approvals'],
        ['Vice Principal',       'vice_principal', 'Academic oversight and discipline'],
        ['Accountant',           'accountant',     'Fee collection, payroll, and financial reports'],
        ['Teacher',              'teacher',        'Academic staff — routine, marks, attendance'],
        ['Data Entry Operator',  'data_operator',  'Student admissions and data entry'],
        ['Student',              'student',        'Enrolled student portal'],
        ['Guardian',             'guardian',       'Parent or guardian portal'],
        ['Librarian',            'librarian',      'Library and document management'],
        ['Store Manager',        'store_manager',  'Inventory and asset management'],
        ['HR Manager',           'hr_manager',     'Staff HR and payroll management'],
        ['Exam Controller',      'exam_controller','Exam logistics, seat plans, and marks approval'],
    ];
    $rStmt = $pdo->prepare('INSERT IGNORE INTO roles (role_name, role_slug, description) VALUES (?,?,?)');
    foreach ($roles as $r) $rStmt->execute($r);

    // Permissions (module-based)
    $permissions = [
        // Setup
        ['setup.view',   'setup',   'View Setup',           'View system settings'],
        ['setup.edit',   'setup',   'Edit Setup',           'Edit system settings'],
        // Users
        ['users.view',   'users',   'View Users',           'List all users'],
        ['users.create', 'users',   'Create Users',         'Add new users'],
        ['users.edit',   'users',   'Edit Users',           'Modify users'],
        ['users.delete', 'users',   'Delete Users',         'Remove users'],
        ['roles.manage', 'users',   'Manage Roles',         'Create and edit roles'],
        // Academic
        ['academic.view',    'academic','View Academic',     'View sessions, classes, subjects'],
        ['academic.manage',  'academic','Manage Academic',   'Create/edit sessions, classes, subjects'],
        ['routine.view',     'academic','View Routine',      'View class timetables'],
        ['routine.manage',   'academic','Manage Routine',    'Create/edit timetables'],
        // Students
        ['students.view',    'students','View Students',     'List and view student profiles'],
        ['students.create',  'students','Admit Students',    'New student admissions'],
        ['students.edit',    'students','Edit Students',     'Modify student data'],
        ['students.promote', 'students','Promote Students',  'End-of-year promotions'],
        ['students.tc',      'students','Issue TC',          'Generate Transfer Certificates'],
        // Exams
        ['exams.view',       'exams','View Exams',           'View exam schedules'],
        ['exams.manage',     'exams','Manage Exams',         'Create exam parameters'],
        ['marks.enter',      'exams','Enter Marks',          'Input student marks'],
        ['marks.approve',    'exams','Approve Marks',        'Verify and publish results'],
        ['seats.manage',     'exams','Manage Seat Plans',    'Assign exam seats'],
        // Finance
        ['finance.view',     'finance','View Finance',       'View fees and reports'],
        ['fees.collect',     'finance','Collect Fees',       'Record fee payments'],
        ['waivers.request',  'finance','Request Waiver',     'Submit waiver requests'],
        ['waivers.approve',  'finance','Approve Waiver',     'Approve/reject waivers'],
        ['expenses.manage',  'finance','Manage Expenses',    'Log institutional expenses'],
        ['payroll.view',     'finance','View Payroll',       'View payroll runs'],
        ['payroll.manage',   'finance','Manage Payroll',     'Process payroll'],
        // HR
        ['hr.view',          'hr','View HR',                 'View staff profiles'],
        ['hr.manage',        'hr','Manage HR',               'Create/edit staff profiles'],
        ['leave.approve',    'hr','Approve Leave',           'Review leave applications'],
        ['attendance.mark',  'hr','Mark Attendance',         'Mark staff attendance'],
        // Inventory
        ['inventory.view',   'inventory','View Inventory',   'View assets and stock'],
        ['inventory.manage', 'inventory','Manage Inventory', 'Add/edit assets and consumables'],
        // ECA
        ['eca.view',         'eca','View ECA',               'View clubs and events'],
        ['eca.manage',       'eca','Manage ECA',             'Create clubs and events'],
        // Communication
        ['sms.send',         'communication','Send SMS',      'Send SMS to users'],
        ['documents.issue',  'communication','Issue Documents','Generate certificates'],
        ['incidents.manage', 'communication','Manage Incidents','Log disciplinary actions'],
        // Reports
        ['reports.view',     'reports','View Reports',        'Access all reports'],
    ];
    $pStmt = $pdo->prepare('INSERT IGNORE INTO permissions (permission_key, module, label, description) VALUES (?,?,?,?)');
    foreach ($permissions as $p) $pStmt->execute($p);

    // Grant super_admin all permissions
    $superRoleId = $pdo->query("SELECT id FROM roles WHERE role_slug='super_admin'")->fetchColumn();
    $allPermIds  = $pdo->query("SELECT id FROM permissions")->fetchAll(PDO::FETCH_COLUMN);
    $rpStmt = $pdo->prepare('INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (?,?)');
    foreach ($allPermIds as $pid) $rpStmt->execute([$superRoleId, $pid]);

    // Admin user
    $hash = password_hash($adm_pass, PASSWORD_BCRYPT);
    $pdo->prepare('INSERT IGNORE INTO users (username, password_hash, full_name, email, status) VALUES (?,?,?,?,?)')
        ->execute([$adm_user, $hash, $adm_name, $adm_email, 'active']);
    $adminId = $pdo->lastInsertId() ?: $pdo->query("SELECT id FROM users WHERE username='" . addslashes($adm_user) . "'")->fetchColumn();
    $pdo->prepare('INSERT IGNORE INTO user_roles (user_id, role_id) VALUES (?,?)')->execute([$adminId, $superRoleId]);

    // System settings
    $settings = [
        ['school_name',        $sch_name,    'general'],
        ['school_address',     $sch_addr,    'general'],
        ['school_phone',       $sch_phone,   'general'],
        ['school_email',       $sch_email,   'general'],
        ['school_logo',        '',           'general'],
        ['school_type',        $sch_type,    'general'],
        ['academic_board',     $sch_board,   'academic'],
        ['current_session_id', '0',          'academic'],
        ['currency_symbol',    '৳',          'finance'],
        ['receipt_prefix',     'RCP',        'finance'],
        ['date_format',        'Y-m-d',      'general'],
        ['timezone',           'Asia/Dhaka', 'general'],
        ['sms_gateway',        'greenweb',   'communication'],
        ['sms_api_key',        '',           'communication'],
        ['sms_sender_id',      '',           'communication'],
        ['working_days',       'Sat,Sun,Mon,Tue,Wed', 'academic'],
        ['per_page',               '25',    'general'],
        ['system_version',         '1.0.0', 'general'],
        ['allow_partial_payment',  'no',    'finance'],
        ['partial_requires_approval','yes', 'finance'],
        ['partial_min_percent',    '100',   'finance'],
    ];
    $sStmt = $pdo->prepare('INSERT IGNORE INTO system_settings (meta_key, meta_value, meta_group) VALUES (?,?,?)');
    foreach ($settings as $s) $sStmt->execute($s);

    // Default leave types
    $leaveTypes = [
        ['Casual Leave',    10, 1, 'all'],
        ['Sick Leave',      14, 1, 'all'],
        ['Maternity Leave', 90, 1, 'all'],
        ['Earned Leave',    15, 1, 'all'],
        ['Half-Pay Leave',  20, 1, 'all'],
    ];
    $ltStmt = $pdo->prepare('INSERT IGNORE INTO leave_types (leave_name, annual_quota, is_paid, applicable_to) VALUES (?,?,?,?)');
    foreach ($leaveTypes as $lt) $ltStmt->execute($lt);

    // Default fee categories
    $feeCategories = [
        ['Tuition Fee',       'tuition',   'Monthly tuition charge'],
        ['Admission Fee',     'admission', 'One-time admission charge'],
        ['Session Charge',    'session',   'Annual session fee'],
        ['Exam Fee',          'exam',      'Per-exam examination fee'],
        ['Library Fee',       'library',   'Annual library access fee'],
        ['Transport Fee',     'transport', 'Monthly transport charge'],
        ['Late Fine',         'fine',      'Late payment fine'],
    ];
    $fcStmt = $pdo->prepare('INSERT IGNORE INTO fee_categories (category_name, category_type, description) VALUES (?,?,?)');
    foreach ($feeCategories as $fc) $fcStmt->execute($fc);

    // Default expense & income categories
    $expCats = ['Salary','Utilities','Maintenance','Stationery','Furniture','Equipment','Event Expenses','Miscellaneous'];
    $ecStmt  = $pdo->prepare('INSERT IGNORE INTO expense_categories (category_name) VALUES (?)');
    foreach ($expCats as $ec) $ecStmt->execute([$ec]);

    $incCats = ['Donation','Venue Rental','Canteen Revenue','Miscellaneous Income'];
    $icStmt  = $pdo->prepare('INSERT IGNORE INTO income_categories (category_name) VALUES (?)');
    foreach ($incCats as $ic) $icStmt->execute([$ic]);

    // Default asset & consumable categories
    foreach (['Electronics','Furniture','Lab Equipment','Sports Equipment','Musical Instruments','Vehicles'] as $ac)
        $pdo->prepare('INSERT IGNORE INTO asset_categories (category_name) VALUES (?)')->execute([$ac]);

    foreach (['Books','Notebooks (Khata)','Stationery','Uniforms','Cleaning Supplies','Lab Consumables'] as $cc)
        $pdo->prepare('INSERT IGNORE INTO consumable_categories (category_name) VALUES (?)')->execute([$cc]);

    // Default groups / streams
    $groups = [['Science','SCI'],['Commerce','COM'],['Arts','ART'],['Business Studies','BUS']];
    $gsStmt = $pdo->prepare('INSERT IGNORE INTO groups_stream (group_name, group_code) VALUES (?,?)');
    foreach ($groups as $g) $gsStmt->execute($g);

    // Default account — every install needs at least one cash account to start fee collection
    $pdo->prepare('INSERT IGNORE INTO accounts (account_name, account_type, current_balance, notes) VALUES (?,?,?,?)')
        ->execute(['Main Cash', 'cash', 0.00, 'Primary cash register — created by installer']);
}

$h = fn(string $s) => htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
$old = fn(string $k, string $d = '') => $h($_POST[$k] ?? $d);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EMS — Installation Wizard</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<style>
  body{background:linear-gradient(135deg,#1a56db 0%,#0e9f6e 100%);min-height:100vh;display:flex;align-items:center;justify-content:center;font-family:'Segoe UI',sans-serif;}
  .wizard-card{background:#fff;border-radius:16px;box-shadow:0 20px 60px rgba(0,0,0,.25);max-width:720px;width:100%;overflow:hidden;}
  .wizard-header{background:linear-gradient(135deg,#1a56db,#1e40af);color:#fff;padding:2rem 2.5rem;}
  .wizard-header h2{font-weight:700;margin:0;}
  .wizard-body{padding:2rem 2.5rem;}
  .step-tabs{display:flex;gap:.5rem;margin-bottom:1.5rem;}
  .step-tab{flex:1;text-align:center;padding:.5rem;border-radius:8px;font-size:.85rem;font-weight:600;color:#64748b;background:#f1f5f9;}
  .step-tab.active{background:#1a56db;color:#fff;}
  .step-tab.done{background:#0e9f6e;color:#fff;}
  .form-label{font-weight:600;font-size:.875rem;color:#374151;}
  .section-title{font-size:.8rem;text-transform:uppercase;letter-spacing:.08em;color:#6b7280;font-weight:700;border-bottom:1px solid #e5e7eb;padding-bottom:.4rem;margin-bottom:1rem;}
</style>
</head>
<body>
<div class="wizard-card">
  <div class="wizard-header">
    <div class="d-flex align-items-center gap-3">
      <i class="bi bi-mortarboard-fill fs-1"></i>
      <div>
        <h2>Education Management System</h2>
        <p class="mb-0 opacity-75">Bangladesh School & College Platform — v1.0</p>
      </div>
    </div>
  </div>
  <div class="wizard-body">

    <?php if ($success): ?>
    <!-- ── SUCCESS ─────────────────────────────────────── -->
    <div class="text-center py-4">
      <div class="mb-3"><i class="bi bi-check-circle-fill text-success" style="font-size:4rem;"></i></div>
      <h4 class="fw-bold text-success">Installation Complete!</h4>
      <p class="text-muted">Database created with <?= count(explode('-- SPLIT --', get_schema_sql())) ?> tables. All seed data loaded.</p>
      <div class="alert alert-warning text-start">
        <i class="bi bi-exclamation-triangle-fill me-2"></i>
        <strong>Security:</strong> Delete or restrict access to <code>install.php</code> immediately before going live.
      </div>
      <a href="index.php" class="btn btn-primary btn-lg px-5">
        <i class="bi bi-box-arrow-in-right me-2"></i>Go to Login
      </a>
    </div>

    <?php else: ?>

    <!-- Step indicators -->
    <div class="step-tabs">
      <div class="step-tab <?= $step >= 1 ? ($step > 1 ? 'done' : 'active') : '' ?>">
        <i class="bi bi-database me-1"></i>Database
      </div>
      <div class="step-tab <?= $step >= 2 ? ($step > 2 ? 'done' : 'active') : '' ?>">
        <i class="bi bi-building me-1"></i>Institute
      </div>
      <div class="step-tab <?= $step >= 3 ? 'active' : '' ?>">
        <i class="bi bi-person-gear me-1"></i>Admin Account
      </div>
    </div>

    <?php if (!empty($errors)): ?>
    <div class="alert alert-danger">
      <i class="bi bi-x-circle-fill me-2"></i>
      <ul class="mb-0 ps-3">
        <?php foreach ($errors as $e): ?><li><?= $h($e) ?></li><?php endforeach; ?>
      </ul>
    </div>
    <?php endif; ?>

    <form method="POST" autocomplete="off">
      <input type="hidden" name="step" value="<?= $step === 1 ? 2 : ($step === 2 ? 3 : 3) ?>">

      <?php if ($step === 1): ?>
      <!-- ── STEP 1: Database ─────────────────────────── -->
      <p class="section-title">MySQL / MariaDB Connection</p>
      <div class="row g-3">
        <div class="col-md-8">
          <label class="form-label">Database Host</label>
          <input name="db_host" class="form-control" value="<?= $old('db_host','localhost') ?>" required>
        </div>
        <div class="col-md-4">
          <label class="form-label">Port</label>
          <input name="db_port" class="form-control" value="<?= $old('db_port','3306') ?>" required>
        </div>
        <div class="col-md-12">
          <label class="form-label">Database Name <small class="text-muted">(will be created if not exists)</small></label>
          <input name="db_name" class="form-control" value="<?= $old('db_name','ems_db') ?>" required placeholder="ems_db">
        </div>
        <div class="col-md-6">
          <label class="form-label">DB Username</label>
          <input name="db_user" class="form-control" value="<?= $old('db_user','root') ?>" required>
        </div>
        <div class="col-md-6">
          <label class="form-label">DB Password</label>
          <input type="password" name="db_pass" class="form-control" value="">
        </div>
      </div>
      <div class="mt-4 d-flex justify-content-end">
        <button type="submit" class="btn btn-primary px-5">Next <i class="bi bi-arrow-right ms-1"></i></button>
      </div>

      <?php elseif ($step === 2): ?>
      <!-- ── STEP 2: Institute Info ────────────────────── -->
      <!-- Pass DB fields hidden -->
      <input type="hidden" name="db_host" value="<?= $old('db_host','localhost') ?>">
      <input type="hidden" name="db_port" value="<?= $old('db_port','3306') ?>">
      <input type="hidden" name="db_name" value="<?= $old('db_name','ems_db') ?>">
      <input type="hidden" name="db_user" value="<?= $old('db_user','root') ?>">
      <input type="hidden" name="db_pass" value="<?= $h($_POST['db_pass'] ?? '') ?>">

      <p class="section-title">Institute Information</p>
      <div class="row g-3">
        <div class="col-12">
          <label class="form-label">School / College Name <span class="text-danger">*</span></label>
          <input name="school_name" class="form-control" value="<?= $old('school_name') ?>" required placeholder="e.g. Dhaka Model High School">
        </div>
        <div class="col-md-6">
          <label class="form-label">Institute Type</label>
          <select name="school_type" class="form-select">
            <option value="school" <?= $old('school_type') === 'school' ? 'selected' : '' ?>>School (Playgroup–SSC)</option>
            <option value="college" <?= $old('school_type') === 'college' ? 'selected' : '' ?>>College (HSC)</option>
            <option value="school_and_college" <?= $old('school_type') === 'school_and_college' ? 'selected' : '' ?>>School & College</option>
            <option value="madrasa" <?= $old('school_type') === 'madrasa' ? 'selected' : '' ?>>Madrasa</option>
          </select>
        </div>
        <div class="col-md-6">
          <label class="form-label">Education Board</label>
          <select name="academic_board" class="form-select">
            <?php foreach (['DEB'=>'Dhaka Board','RAJ'=>'Rajshahi Board','CHI'=>'Chittagong Board','CUM'=>'Comilla Board','BAR'=>'Barisal Board','JES'=>'Jessore Board','SYL'=>'Sylhet Board','MYM'=>'Mymensingh Board','DIN'=>'Dinajpur Board','NCTB'=>'NCTB','EIIN'=>'EIIN-based'] as $k=>$v): ?>
            <option value="<?= $k ?>" <?= $old('academic_board') === $k ? 'selected' : '' ?>><?= $v ?></option>
            <?php endforeach; ?>
          </select>
        </div>
        <div class="col-12">
          <label class="form-label">Address</label>
          <input name="school_address" class="form-control" value="<?= $old('school_address') ?>" placeholder="Street, Thana, District">
        </div>
        <div class="col-md-6">
          <label class="form-label">Phone</label>
          <input name="school_phone" class="form-control" value="<?= $old('school_phone') ?>">
        </div>
        <div class="col-md-6">
          <label class="form-label">Email</label>
          <input type="email" name="school_email" class="form-control" value="<?= $old('school_email') ?>">
        </div>
      </div>
      <div class="mt-4 d-flex justify-content-end">
        <button type="submit" class="btn btn-primary px-5">Next <i class="bi bi-arrow-right ms-1"></i></button>
      </div>

      <?php else: ?>
      <!-- ── STEP 3: Admin account + install ──────────── -->
      <input type="hidden" name="db_host" value="<?= $old('db_host','localhost') ?>">
      <input type="hidden" name="db_port" value="<?= $old('db_port','3306') ?>">
      <input type="hidden" name="db_name" value="<?= $old('db_name','ems_db') ?>">
      <input type="hidden" name="db_user" value="<?= $old('db_user','root') ?>">
      <input type="hidden" name="db_pass" value="<?= $h($_POST['db_pass'] ?? '') ?>">
      <input type="hidden" name="school_name" value="<?= $old('school_name') ?>">
      <input type="hidden" name="school_address" value="<?= $old('school_address') ?>">
      <input type="hidden" name="school_phone" value="<?= $old('school_phone') ?>">
      <input type="hidden" name="school_email" value="<?= $old('school_email') ?>">
      <input type="hidden" name="school_type" value="<?= $old('school_type','school') ?>">
      <input type="hidden" name="academic_board" value="<?= $old('academic_board','DEB') ?>">

      <p class="section-title">Super Administrator Account</p>
      <div class="row g-3">
        <div class="col-12">
          <label class="form-label">Full Name</label>
          <input name="admin_name" class="form-control" value="<?= $old('admin_name','System Administrator') ?>">
        </div>
        <div class="col-md-6">
          <label class="form-label">Username</label>
          <input name="admin_username" class="form-control" value="<?= $old('admin_username','admin') ?>" required>
        </div>
        <div class="col-md-6">
          <label class="form-label">Email</label>
          <input type="email" name="admin_email" class="form-control" value="<?= $old('admin_email') ?>">
        </div>
        <div class="col-md-6">
          <label class="form-label">Password <span class="text-danger">*</span> <small class="text-muted">(min 6 chars)</small></label>
          <input type="password" name="admin_password" class="form-control" required>
        </div>
        <div class="col-md-6">
          <label class="form-label">Confirm Password</label>
          <input type="password" name="admin_password2" class="form-control" required>
        </div>
      </div>

      <div class="alert alert-info mt-3">
        <i class="bi bi-info-circle me-2"></i>
        This will create <strong><?= count(explode('-- SPLIT --', get_schema_sql())) ?> database tables</strong>, seed default roles, permissions, fee categories, leave types, and system settings.
      </div>

      <div class="mt-3 d-flex justify-content-end">
        <button type="submit" class="btn btn-success btn-lg px-5">
          <i class="bi bi-rocket-takeoff me-2"></i>Install EMS
        </button>
      </div>
      <?php endif; ?>
    </form>

    <?php endif; ?>
  </div><!-- /wizard-body -->
</div><!-- /wizard-card -->

<script>
// Password match check on step 3
document.querySelector('form')?.addEventListener('submit', function(e){
  const p1 = document.querySelector('[name=admin_password]');
  const p2 = document.querySelector('[name=admin_password2]');
  if (p1 && p2 && p1.value !== p2.value) {
    e.preventDefault();
    alert('Passwords do not match.');
    p2.focus();
  }
});
</script>
</body>
</html>
