<?php
// Auto-generated by EMS Installer. Do not edit manually.
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'ems_db');
define('DB_USER', 'root');
define('DB_PASS', '');