<?php
include 'header.php';
?>
<?php
if (isset($_GET['approve_id'])) {
    // Only Admin (role 0) and Manager (role 1) can approve orders
    if ($_SESSION['role'] != 1 && $_SESSION['role'] != 0) {
        echo "<script>alert('You are not authorized to approve orders.'); window.location.href='orders.php';</script>";
        exit();
    }
    $approve_id = $_GET['approve_id'];
    $stmt = $conn->prepare("UPDATE orders SET order_status='1', approved_at=NOW(), approved_by=? WHERE id=?");
    $stmt->bind_param("ii", $_SESSION['user_id'], $approve_id);
    if ($stmt->execute()) {
        echo "<script>alert('Order approved successfully.'); window.location.href='orders.php';</script>";
        exit();
    } else {
        echo "<script>alert('An error occurred while approving the order. Please try again.'); window.location.href='orders.php';</script>";
        exit();
    }
    $stmt->close();
}
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    if (isset($_POST['add_order'])) {
        $shop_id = $_POST['shop_id'];
        $route_id = $_POST['route_id'];
        $order_date = $_POST['order_date'];
        $delivery_date = $_POST['delivery_date'];
        $order_status = $_POST['order_status'];
        $user_id = $_SESSION['user_id'];
        $status = $_POST['status'];
        $company_id = $_SESSION['company_id'];
        $remarks = $_POST['remarks'];
        $latitude = $_POST['latitude'];
        $longitude = $_POST['longitude'];

        $stmt = $conn->prepare("INSERT INTO orders (shop_id, route_id, order_date, delivery_date, order_status, created_by, created_at, status, company_id, remarks, latitude, longitude) VALUES (?, ?, ?, ?, ?, ?, NOW(), ?, ?, ?, ?, ?)");
        $stmt->bind_param("iissiiiiisdd", $shop_id, $route_id, $order_date, $delivery_date, $order_status, $user_id, $status, $company_id, $remarks, $latitude, $longitude);
        
        if ($stmt->execute()) {
            $order_id = $stmt->insert_id;
            $stmt->close();
            header("Location: order_item.php?order_id=$order_id");
            exit();
        } else {
            echo "<script>alert('An error occurred. Please try again.'); window.location.href='orders.php';</script>";
            exit();
        }
    }
    if (isset($_POST['update_order'])) {
        $order_id = $_GET['order_edit_id'];
        $order_date = $_POST['order_date'];
        $delivery_date = $_POST['delivery_date'];
        $order_status_post = $_POST['order_status'];
        $shop_id = $_POST['shop_id'];
        $route_id = $_POST['route_id'];
        $status = $_POST['status'];

        // check if approved
        $stmt = $conn->prepare("SELECT order_status FROM orders WHERE id = ?");
        $stmt->bind_param("i", $order_id);
        $stmt->execute();
        $result = $stmt->get_result();
        $row = $result->fetch_assoc();
        if ($row['order_status'] == 1) {
            echo "<script>alert('This order has already been approved.'); window.location.href='orders.php';</script>";
            exit();
        }
        $stmt->close();

        $stmt = $conn->prepare("UPDATE orders SET shop_id=?, route_id=?, order_date=?, delivery_date=?, order_status=?, status=? WHERE id=?");
        $stmt->bind_param("iissiii", $shop_id, $route_id, $order_date, $delivery_date, $order_status_post, $status, $order_id);
        $stmt->execute();
        $stmt->close();

        header("Location: orders.php");
        exit();
    }
}
      
 
?>
    <div class="print-header">
           <h1><?php echo APP_NAME; ?> Report</h1>
        <p>Generated by: <?php echo $_SESSION['user_id'] . "@".$_SESSION['username']. " | C: " .
         $_SESSION['company_id']." ";?>| Date: <?php echo date("Y-m-d"); ?></p>

    </div>


    <div class="container">

        <div class="text-center" style="text-align: center; margin: 30px 0;">
            <h2 style="font-weight: 300; font-size: 2rem;">Order  List</h2>
            <p style="color: #666;">Create and manage order.</p>
        </div>

        <div class="glass-panel form-section">
            <span class="section-title">New Order  Add</span>
            <form method="POST">


                <?php if (isset($_GET['order_edit_id'])) {
                    $order_edit_id = $_GET['order_edit_id'];
                    $query = "SELECT * FROM orders WHERE id='$order_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $order_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                    <div class="col-1">
                        <label>Route Name</label>
                        
                        <select name="route_id" id="route_id" onchange="getShopsByRouteId(this.value)" required>
                            <option value="">Select Route</option>
                            <?php
                            $query = "SELECT id, route_name FROM routes WHERE status = 1 AND company_id='{$_SESSION['company_id']}' ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($order_data['route_id']) && $order_data['route_id'] == $row['id']) ? 'selected' : '';
                                    echo "<option value='" . $row['id'] . "' $selected>" . $row['route_name'] . "</option>";
                                }
                            }
                            ?>
                        </select>
                    </div>


                    <div class="col-1">
                    
                        
                        <label>Shop Name</label>
                        <select name="shop_id" id="shop_id" required>
                            <?php if (isset($_GET['shop_id'])): ?>
                                <option value="<?php echo $_GET['shop_id']; ?>" selected><?php echo $_GET['shop_name']; ?></option>
                            <?php else: ?>
                                <option value="">Select Shop</option>
                            <?php endif; ?>
                            <?php
                            $route_id = isset($_POST['route_id']) ? $_POST['route_id'] : '';
                            $query = "SELECT id, shop_name FROM shops WHERE route_id='$route_id' ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($order_data['shop_id']) && $order_data['shop_id'] == $row['id']) ? 'selected' : '';
                                    echo '<option value="' . $row['id'] . '" ' . $selected . '>' . $row['shop_name'] . '</option>';
                                }
                            }
                            ?>
                        </select>

                       <script>
    $(document).ready(function() {
        // Initialize Select2 on the Add/Edit form elements
        $('#route_id').select2({
            width: '100%',
            placeholder: "Select Route"
        });
        $('#shop_id').select2({
            width: '100%',
            placeholder: "Select Shop"
        });

        // Optional: Initialize on the Search Filter elements at the top
        $('select[name="search_route_id"]').select2({ width: '100%' });
        $('select[name="search_shop_id"]').select2({ width: '100%' });
    });

    function getShopsByRouteId(route_id) {
        // Clear the current shop selection
        $('#shop_id').empty();
        
        $.ajax({
            url: 'get_shops_by_route_id.php', // I removed ?route_id= here because you are sending it in `data` below
            type: 'GET',
            data: {
                route_id: route_id
            },
            success: function(response) {
                // Update the select options
                $('#shop_id').html(response);
                
                // IMPORTANT: Trigger the change event so Select2 updates the list
                $('#shop_id').trigger('change');
            },
            error: function(xhr, status, error) {
                console.log("Error: " + error);
            }
        });
    }
</script>
                    </div>
                    
                   <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                  
                    <div>
                    <label>Order Date</label>
                    <input type="date" class="form-control" id="order_date" name="order_date" value="<?php echo htmlspecialchars(isset($order_data['order_date']) ? $order_data['order_date'] : date('Y-m-d')); ?>" required>
                    </div>
                    <div>
                    <label>Delivery Date</label>
                    <input type="date" class="form-control" id="delivery_date" name="delivery_date" value="<?php echo htmlspecialchars(isset($order_data['delivery_date']) ? $order_data['delivery_date'] : date('Y-m-d', strtotime('+1 days'))); ?>" required>
                    </div>
                    
                    <div><label>Order Status</label>
                    <select name="order_status">
                        <option value="0" <?php echo isset($shop_data['status']) && $shop_data['status'] == 0 ? 'selected' : ''; ?>>Draft</option>
                        <option value="1" <?php echo isset($shop_data['status']) && $shop_data['status'] == 1 ? 'selected' : ''; ?>>Confirmed</option>

                    </select>
                </div>
                    <div><label>Status</label>
                    <select name="status">
                        <option value="1" <?php echo isset($shop_data['status']) && $shop_data['status'] == 1 ? 'selected' : ''; ?>>Active</option>
                        <option value="0" <?php echo isset($shop_data['status']) && $shop_data['status'] == 0 ? 'selected' : ''; ?>>Inactive</option>
                    </select>
                </div>
                    </div>


                
  <div class="col-1">
                        <label>Remarks</label>
                        
                        <input type="text" placeholder="Remarks" name="remarks" value="<?php echo htmlspecialchars(isset($order_data['remarks']) ? $order_data['remarks'] : ''); ?>">
                    </div>

                    <input type="hidden" id="latitude" name="latitude" >
                    <input type="hidden" id="longitude" name="longitude" >
                    <script>
                        function getLocation() {
                            if (navigator.geolocation) {
                                navigator.geolocation.getCurrentPosition(function(position) {
                                function showError(error) {
                                    alert('Error getting location: ' + error.message);
                                }
                                    document.getElementById("latitude").value = position.coords.latitude;
                                    document.getElementById("longitude").value = position.coords.longitude;
                                });
                            }
                        }
                        getLocation();
                    </script>
                


                </div>
                
                <div class="form-actions">
                    <?php if (isset($order_edit_id)) {
                        echo '<button type="submit" name="update_order" class="btn btn-yellow"><i class="fa-solid fa-edit"></i> Update order</button>';
                    } else {
                        echo '<button type="submit" name="add_order" class="btn btn-yellow"><i class="fa-solid fa-plus"></i> Add order</button>';
                    }

                    ?>
                </div>
            </form>
        </div>

        <div class=" form-section" style="margin-bottom: 20px;">
          
            <form method="GET">


                <?php if (isset($_GET['order_edit_id'])) {
                    $order_edit_id = $_GET['order_edit_id'];
                    $query = "SELECT * FROM orders WHERE id='$order_edit_id'";
                    $result = mysqli_query($conn, $query);
                    if (mysqli_num_rows($result) > 0) {
                        $order_data = mysqli_fetch_assoc($result);
                    }
                }
                ?>
                <div class="desktop-span-2">
                   
                <div class="grid-layout desktop-4" style="grid-template-columns: 1fr 1fr;">
                    <div><label>Date From</label>
                    <input type="date" placeholder="Date" name="date_from" value="<?php echo isset($_GET['date_from']) ? $_GET['date_from'] : date('Y-m-d'); ?>" required>
                    </div>
                    <div><label>Date To</label>
                    <input type="date" placeholder="Date" name="date_to" value="<?php echo isset($_GET['date_to']) ? $_GET['date_to'] : date('Y-m-d'); ?>" required>
                    </div>
                    <div><label>Route Name</label>
                        
                        <select name="search_route_id" >
                            <option value="">All Route</option>
                            <?php
                            $query = "SELECT id, route_name FROM routes WHERE status = 1 ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($_GET['search_route_id']) && $_GET['search_route_id'] == $row['id']) ? 'selected' : '';
                                    echo "<option value='" . $row['id'] . "' $selected>" . $row['route_name'] . "</option>";
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div>
                                                                    
                        
                        <label>Shop Name</label>
                        <select name="search_shop_id" >
                            <option value="">All Shop</option>
                            <?php
                            $query = "SELECT id, shop_name FROM shops WHERE status = 1 ORDER BY id DESC";
                            $result = mysqli_query($conn, $query);
                            if (mysqli_num_rows($result) > 0) {
                                while ($row = mysqli_fetch_assoc($result)) {
                                    $selected = (isset($_GET['search_shop_id']) && $_GET['search_shop_id'] == $row['id']) ? 'selected' : '';
                                    echo '<option value="' . $row['id'] . '" ' . $selected . '>' . $row['shop_name'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </div>
            

                  
                    <div><label>ID</label>
                    <input type="number"  placeholder="All" name="search_id" value="<?php echo htmlspecialchars(isset($_GET['search_id']) ? $_GET['search_id'] : ''); ?>">
                    </div>
                    <div><label>Status</label>
                    <select name="search_status">
                         <option value="">All</option>
                        <option value="1" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 1 ? 'selected' : ''; ?>>Active</option>
                        <option value="0" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 0 ? 'selected' : ''; ?>>Inactive</option>
                        <option value="3" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 3 ? 'selected' : ''; ?>>Draft</option>
                        <option value="4" <?php echo isset($_GET['search_status']) && $_GET['search_status'] == 4 ? 'selected' : ''; ?>>Confirmed</option>

                    </select>
                </div>
                    </div>
                </div>
                
                <div class="form-actions">
                   <button type="submit" name="search_order" class="btn btn-green"><i class="fa-solid fa-search"></i> Search</button>
                </div>
            </form>
        </div>

        <div class="glass-panel printable">
            <div style="display: flex; justify-content: space-between; margin-bottom: 15px; m">
                <span class="section-title" style="margin:0;">All Order </span>
                   <button onclick="window.print()" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.7rem;"><i class="fa-solid fa-file-pdf"></i> / <i class="fa-solid fa-print"></i></button>
     
            </div>

            <div class="table-responsive" id="table">

            <?php
            $search_text='';
            $company_id = $_SESSION['company_id'];
            $user_id = $_SESSION['user_id'];

            // Pagination Logic
            $limit = 20; // Records per page
            $page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
            if ($page < 1) $page = 1;
            $offset = ($page - 1) * $limit;

            $base_query = "SELECT o.*, r.route_name, s.shop_name, u.username as creator_name 
                           FROM orders o 
                           LEFT JOIN routes r ON o.route_id = r.id 
                           LEFT JOIN shops s ON o.shop_id = s.id 
                           LEFT JOIN users u ON o.created_by = u.id 
                           WHERE o.company_id = ?";

            $params = [$company_id];
            $types = "i";

            // Count Query for Total Pages
            $count_query = "SELECT COUNT(*) as total FROM orders o WHERE o.company_id = ?";
            $count_params = [$company_id];
            $count_types = "i";

            if (!isset($_GET['search_id']) && !isset($_GET['search_route_id']) && !isset($_GET['search_shop_id']) && !isset($_GET['search_status']) && !isset($_GET['date_from']) && !isset($_GET['date_to'])) {
                $filter_sql = " AND (o.created_by = ? OR (o.created_by != ? AND o.order_status = 1))";
                $base_query .= $filter_sql;
                $count_query .= $filter_sql;
                
                $params[] = $user_id;
                $params[] = $user_id;
                $types .= "ii";
                
                $count_params[] = $user_id;
                $count_params[] = $user_id;
                $count_types .= "ii";
            } else {
                if (!empty($_GET['search_id'])) {
                    $base_query .= " AND o.id = ?";
                    $count_query .= " AND o.id = ?";
                    $params[] = $_GET['search_id'];
                    $count_params[] = $_GET['search_id'];
                    $types .= "i";
                    $count_types .= "i";
                    $search_text .= " ID: " . htmlspecialchars($_GET['search_id']);
                } else {
                    if (!empty($_GET['search_route_id'])) {
                        $base_query .= " AND o.route_id = ?";
                        $count_query .= " AND o.route_id = ?";
                        $params[] = $_GET['search_route_id'];
                        $count_params[] = $_GET['search_route_id'];
                        $types .= "i";
                        $count_types .= "i";
                        $search_text .= " Route ID: " . htmlspecialchars($_GET['search_route_id']);
                    }
                    if (!empty($_GET['search_shop_id'])) {
                        $base_query .= " AND o.shop_id = ?";
                        $count_query .= " AND o.shop_id = ?";
                        $params[] = $_GET['search_shop_id'];
                        $count_params[] = $_GET['search_shop_id'];
                        $types .= "i";
                        $count_types .= "i";
                        $search_text .= " Shop ID: " . htmlspecialchars($_GET['search_shop_id']);
                    }
                    if (isset($_GET['search_status']) && $_GET['search_status'] !== '') {
                        $status_val = $_GET['search_status'];
                        if ($status_val == 3) {
                            $base_query .= " AND o.order_status = '0'";
                            $count_query .= " AND o.order_status = '0'";
                        } else if ($status_val == 4) {
                            $base_query .= " AND o.order_status = '1'";
                            $count_query .= " AND o.order_status = '1'";
                        } else {
                            $base_query .= " AND o.status = ?";
                            $count_query .= " AND o.status = ?";
                            $params[] = $status_val;
                            $count_params[] = $status_val;
                            $types .= "i";
                            $count_types .= "i";
                        }
                        $search_text .= " Status: $status_val";
                    }
                    if (!empty($_GET['date_from']) && !empty($_GET['date_to'])) {
                        $base_query .= " AND o.order_date BETWEEN ? AND ?";
                        $count_query .= " AND o.order_date BETWEEN ? AND ?";
                        $params[] = $_GET['date_from'];
                        $params[] = $_GET['date_to'];
                        $count_params[] = $_GET['date_from'];
                        $count_params[] = $_GET['date_to'];
                        $types .= "ss";
                        $count_types .= "ss";
                        $search_text .= " Dates: " . htmlspecialchars($_GET['date_from']) . " to " . htmlspecialchars($_GET['date_to']);
                    }
                }
                $filter_sql = " AND (o.created_by = ? OR (o.created_by != ? AND o.order_status = 1))";
                $base_query .= $filter_sql;
                $count_query .= $filter_sql;
                $params[] = $user_id;
                $params[] = $user_id;
                $count_params[] = $user_id;
                $count_params[] = $user_id;
                $types .= "ii";
                $count_types .= "ii";
            }

            // Get total count for pagination
            $stmt_count = $conn->prepare($count_query);
            $stmt_count->bind_param($count_types, ...$count_params);
            $stmt_count->execute();
            $total_records = $stmt_count->get_result()->fetch_assoc()['total'];
            $total_pages = ceil($total_records / $limit);
            $stmt_count->close();

            $base_query .= " ORDER BY o.id DESC LIMIT ? OFFSET ?";
            $params[] = $limit;
            $params[] = $offset;
            $types .= "ii";

            $stmt = $conn->prepare($base_query);
            $stmt->bind_param($types, ...$params);
            $stmt->execute();
            $result = $stmt->get_result();

            if ($search_text != '') {
                echo "<p class='badge bg-green' style='text-align: center; margin-bottom: 10px;' >Search Results for <b>$search_text</b></p>";
            }
            ?>
                <table class="table-simple">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Route Name</th>
                            <th>Shop Name</th>
                            <th>Dates</th>
                            <th class="print-hide">Status</th>
                            <th style="text-align: right;" class="print-hide">Actions</th>
                            <th>Approval</th>
                            <th>Remarks</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $ids='';
                        if ($result->num_rows > 0) {
                            while ($row = $result->fetch_assoc()) {
                                $ids .= $row['id'] . ",";
                                $route_name = $row['route_name'] ?? 'N/A';
                                $shop_name = $row['shop_name'] ?? 'N/A';
                                $created_by_name = $row['creator_name'] ?? 'N/A';

                              echo "
<tr>
    <td >{$row['id']}
    <i class='fa-solid fa-box' 
           style='color: green; margin-right: 10px; cursor: pointer;' 
           onclick=\"window.location.href='order_item.php?order_id={$row['id']}'\">
        </i>
    
    </td>
   
    <td>{$route_name}</td>
     <td>{$shop_name}</td>
    
    <td>{$row['order_date']} {$row['delivery_date']}</td>


  
    <td class='print-hide' style='text-align: center;'>" . 
        ($row['status'] 
            ? "<span class='badge bg-green'>Active</span>" 
            : "<span class='badge bg-red'>Inactive</span>") . " <br>".
        ($row['order_status'] 
            ? "<span class='badge bg-green'>Confirmed</span>" 
            : "<span class='badge bg-yellow'>Draft</span>") . " ".

    "</td>
    <td style='text-align: right;' class='print-hide' >";
if (isset($row['order_status']) && !is_null($row['order_status']) && $row['order_status'] == 1 ) {
            echo "<i class='fa-solid fa-user' style='color: green; cursor: not-allowed;' title='Confirmed records cannot be edited.'></i>";
        } else {
    echo "
        <i class='fa-solid fa-pen' 
           style='color: var(--warning); margin-right: 10px; cursor: pointer;' 
           onclick=\"window.location.href='orders.php?shop_name={$shop_name}& shop_id={$row['shop_id']}&order_edit_id={$row['id']}'\">
        </i>";}

        echo"
    </td>
    <td >" . 
        (isset($row['approved_at']) && !is_null($row['approved_at'])
            ? "<span class='badge bg-green'>Approved</span>" 
            : "<span class='badge bg-red'
            
             onclick=\"if(confirm('Are you sure you want to approve this Order?')) { window.location.href='orders.php?approve_id={$row['id']}'; }\" 
                title='Approve Order'
            
            
            
            >Pending</span>") . 
    "</td>
    <td>{$row['remarks']}   <i class='fa-solid fa-print' style='color: var(--warning); margin-right: 10px; cursor: pointer;' onclick=\"window.location.href='invoices.php?order_ids={$row['id']}'\"></i></td>
</tr>";

// Sub-query for items
$stmt_items = $conn->prepare("
    SELECT oi.quantity, oi.price, i.item_name
    FROM order_items oi
    JOIN items i ON oi.item_id = i.id
    WHERE oi.order_id = ?
");
$stmt_items->bind_param("i", $row['id']);
$stmt_items->execute();
$order_item_result = $stmt_items->get_result();

if ($order_item_result->num_rows > 0) {
    $inv_total = 0.00;
    echo "<tr>
                <td colspan='4'>";
    while ($order_item_row = $order_item_result->fetch_assoc()) {
        $item_name = $order_item_row['item_name'];
        $quantity = $order_item_row['quantity'];
        $price = $order_item_row['price'];
        $total = $price * $quantity;
        $inv_total += $total;

        echo "<strong>{$item_name}</strong>  {$quantity} × " . number_format($price, 2) . " = " . number_format($total, 2). "<br>";
    }
                echo "<br> Total: <strong>" . number_format($inv_total, 2) . "</strong>/=  by [user:{$row['created_by']} @  $created_by_name]</td>
              </tr>";
}
$stmt_items->close();



                            }
                        }
                        ?>
                    </tbody>
                </table>
            </div>

            <!-- Pagination UI -->
            <div class="pagination print-hide" style="display: flex; justify-content: center; align-items: center; gap: 10px; margin-top: 20px;">
                <?php if ($page > 1): ?>
                    <a href="?page=<?php echo $page - 1; ?>&<?php echo http_build_query(array_diff_key($_GET, ['page' => ''])); ?>" class="btn btn-dark" style="padding: 5px 15px;">&laquo; Previous</a>
                <?php endif; ?>
                
                <span style="font-weight: bold;">Page <?php echo $page; ?> of <?php echo $total_pages; ?></span>

                <?php if ($page < $total_pages): ?>
                    <a href="?page=<?php echo $page + 1; ?>&<?php echo http_build_query(array_diff_key($_GET, ['page' => ''])); ?>" class="btn btn-dark" style="padding: 5px 15px;">Next &raquo;</a>
                <?php endif; ?>
            </div>
        </div>

        <div style="text-align: center; margin-top: 10px;">
<button onclick="window.location.href='invoices.php?order_ids=<?php echo rtrim($ids, ','); ?>'" class="btn btn-dark" style="padding: 5px 15px; font-size: 0.7rem; margin-top: 10px;"><i class="fa-solid fa-file-pdf"></i> Generate Report for Listed Orders</button>
        </div>
    </div>

<?php
include 'footer.php';
?>