<?php
// ============================================================
// modules/backup/backup.php
// ============================================================
requireRole(ROLE_ADMIN);

$action = $_POST['action'] ?? $_GET['action'] ?? '';

// ── Token Generation (No AJAX needed) ────────────────────────
if (empty($_SESSION['restore_token'])) {
    $_SESSION['restore_token'] = bin2hex(random_bytes(16));
}
$restoreToken = $_SESSION['restore_token'];

// ── Topology sort: parents before children ───────────────────
function sortTablesByDependency(array $tables): array {
    $deps = array_fill_keys($tables, []);
    $fkRows = dbFetchAll(
        "SELECT TABLE_NAME, REFERENCED_TABLE_NAME
         FROM information_schema.KEY_COLUMN_USAGE
         WHERE TABLE_SCHEMA = DATABASE()
           AND REFERENCED_TABLE_NAME IS NOT NULL"
    );
    foreach ($fkRows as $r) {
        $t = $r['TABLE_NAME'];
        $ref = $r['REFERENCED_TABLE_NAME'];
        if (isset($deps[$t]) && $ref !== $t) {
            $deps[$t][] = $ref;
        }
    }

    $sorted  = [];
    $visited = [];

    function topoVisit(string $table, array &$deps, array &$visited, array &$sorted): void {
        if (isset($visited[$table])) return;
        $visited[$table] = true;
        foreach ($deps[$table] ?? [] as $dep) {
            topoVisit($dep, $deps, $visited, $sorted);
        }
        $sorted[] = $table;
    }

    foreach ($tables as $t) {
        topoVisit($t, $deps, $visited, $sorted);
    }
    return $sorted;
}

// ── Pure-PHP SQL dump ────────────────────────────────────────
function generateSqlDump(): string {
    $out   = [];
    $out[] = '-- ============================================================';
    $out[] = '-- SQL Backup generated by ' . APP_NAME;
    $out[] = '-- Date    : ' . date('Y-m-d H:i:s');
    $out[] = '-- ============================================================';
    $out[] = '';
    $out[] = 'SET FOREIGN_KEY_CHECKS=0;';
    $out[] = 'SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";';
    $out[] = 'SET time_zone="+00:00";';
    $out[] = '';

    $rawTables = array_map(fn($r) => reset($r), dbFetchAll('SHOW TABLES'));
    $tables    = sortTablesByDependency($rawTables);

    foreach (array_reverse($tables) as $table) {
        $out[] = "DROP TABLE IF EXISTS `$table`;";
    }
    $out[] = '';

    foreach ($tables as $table) {
        $createRow = dbFetch("SHOW CREATE TABLE `$table`");
        $createSql = $createRow['Create Table'] ?? '';

        $out[] = "-- --------------------------------------------------------";
        $out[] = "-- Table: `$table`";
        $out[] = "-- --------------------------------------------------------";
        $out[] = $createSql . ';';
        $out[] = '';

        $countRow = dbFetch("SELECT COUNT(*) AS cnt FROM `$table`");
        if ((int)($countRow['cnt'] ?? 0) === 0) continue;

        $chunkSize = 500;
        $offset    = 0;
        while (true) {
            $rows = dbFetchAll("SELECT * FROM `$table` LIMIT $chunkSize OFFSET $offset");
            if (!$rows) break;

            $cols = '`' . implode('`, `', array_keys($rows[0])) . '`';
            $valueGroups = [];
            foreach ($rows as $r) {
                $vals = array_map(function ($v) {
                    if ($v === null)    return 'NULL';
                    if (is_numeric($v)) return $v;
                    return "'" . addslashes((string)$v) . "'";
                }, array_values($r));
                $valueGroups[] = '(' . implode(', ', $vals) . ')';
            }
            foreach (array_chunk($valueGroups, 100) as $batch) {
                $out[] = "INSERT INTO `$table` ($cols) VALUES";
                $out[] = implode(",\n", $batch) . ';';
            }
            $offset += $chunkSize;
            if (count($rows) < $chunkSize) break;
        }
        $out[] = '';
    }

    $out[] = 'SET FOREIGN_KEY_CHECKS=1;';
    return implode("\n", $out);
}

// ── SQL statement splitter ────────────────────────────────────
function splitSqlStatements(string $sql): array {
    $statements = [];
    $len        = strlen($sql);
    $i          = 0;
    $current    = '';
    $inSingle   = false;
    $inDouble   = false;

    while ($i < $len) {
        $ch   = $sql[$i];
        $next = $sql[$i + 1] ?? '';

        if (!$inSingle && !$inDouble && $ch === '-' && $next === '-') {
            while ($i < $len && $sql[$i] !== "\n") $i++;
            $i++;
            continue;
        }

        if (!$inDouble && $ch === "'") {
            if ($inSingle && $next === "'") {
                $current .= "''";
                $i += 2;
                continue;
            }
            $inSingle = !$inSingle;
            $current .= $ch;
            $i++;
            continue;
        }

        if (!$inSingle && $ch === '"') {
            if ($inDouble && $next === '"') {
                $current .= '""';
                $i += 2;
                continue;
            }
            $inDouble = !$inDouble;
            $current .= $ch;
            $i++;
            continue;
        }

        if (($inSingle || $inDouble) && $ch === '\\') {
            $current .= $ch . $next;
            $i += 2;
            continue;
        }

        if (!$inSingle && !$inDouble && $ch === ';') {
            $stmt = trim($current);
            if ($stmt !== '') {
                $statements[] = $stmt;
            }
            $current = '';
            $i++;
            continue;
        }

        $current .= $ch;
        $i++;
    }

    $stmt = trim($current);
    if ($stmt !== '') {
        $statements[] = $stmt;
    }

    return $statements;
}

// ── Download ─────────────────────────────────────────────────
if ($action === 'download_sql') {
    $slug     = preg_replace('/[^a-zA-Z0-9_-]/', '_', APP_NAME);
    $filename = 'backup_' . $slug . '_' . date('Y-m-d_His') . '.sql';

    logAction('EXPORT', 'backup', null, 'Admin downloaded SQL backup: ' . $filename);

    if (ob_get_level()) ob_end_clean();
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');
    echo generateSqlDump();
    exit;
}

// ── Restore ──────────────────────────────────────────────────
if ($action === 'restore_db') {
    if (
        empty($_POST['confirm_token']) ||
        $_POST['confirm_token'] !== ($_SESSION['restore_token'] ?? '')
    ) {
        flash('error', 'Invalid confirmation token. Please refresh and try again.');
        redirect('backup');
    }
    unset($_SESSION['restore_token']); // Consume token

    if (empty($_FILES['sql_file']['tmp_name'])) {
        flash('error', 'No file uploaded.');
        redirect('backup');
    }

    $origName = $_FILES['sql_file']['name'] ?? '';
    if (strtolower(pathinfo($origName, PATHINFO_EXTENSION)) !== 'sql') {
        flash('error', 'Only .sql files are accepted.');
        redirect('backup');
    }

    $sql = file_get_contents($_FILES['sql_file']['tmp_name']);
    if (!$sql) {
        flash('error', 'Could not read the uploaded file.');
        redirect('backup');
    }

    $statements = splitSqlStatements($sql);

    if (empty($statements)) {
        flash('error', 'No valid SQL statements found in the uploaded file.');
        redirect('backup');
    }

    $errors  = [];
    $count   = 0;

    try { dbQuery('SET FOREIGN_KEY_CHECKS=0'); } catch (Throwable $e) {}
    try { dbQuery('SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO"'); } catch (Throwable $e) {}

    foreach ($statements as $idx => $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '') continue;

        if (preg_match('/^SET\s+(FOREIGN_KEY_CHECKS|SQL_MODE|time_zone)/i', $stmt)) {
            continue;
        }

        try {
            dbQuery($stmt);
            $count++;
        } catch (Throwable $e) {
            $errors[] = [
                'n'   => $idx + 1,
                'sql' => substr($stmt, 0, 120),
                'err' => $e->getMessage(),
            ];
        }
    }

    try { dbQuery('SET FOREIGN_KEY_CHECKS=1'); } catch (Throwable $e) {}

    logAction(
        'IMPORT', 'backup', null,
        "Admin restored DB from: $origName ($count statements, " . count($errors) . " errors)"
    );

    if ($errors) {
        $_SESSION['restore_errors'] = $errors;
        flash('warning', count($errors) . ' error(s) during restore. ' . $count . ' statements ran. See details below.');
    } else {
        flash('success', "Restore complete — $count statements executed successfully.");
    }
    redirect('backup');
}

// ── Page data ────────────────────────────────────────────────
$pageTitle  = 'Backup & Restore';
$sizeRow    = dbFetch("SELECT ROUND(SUM(data_length+index_length),0) AS size
                       FROM information_schema.tables WHERE table_schema=DATABASE()");
$dbSize     = $sizeRow ? (int)$sizeRow['size'] : 0;
$tableCount = count(dbFetchAll('SHOW TABLES'));

function formatBytes(int $bytes): string {
    if ($bytes >= 1048576) return round($bytes / 1048576, 2) . ' MB';
    if ($bytes >= 1024)    return round($bytes / 1024, 1)    . ' KB';
    return $bytes . ' B';
}

$logs = dbFetchAll(
    "SELECT * FROM action_logs WHERE module='backup' ORDER BY created_at DESC LIMIT 10"
) ?: [];

$restoreErrors = $_SESSION['restore_errors'] ?? [];
unset($_SESSION['restore_errors']);

require_once BASE_PATH . '/includes/header.php';
?>

<style>
/* Centered, modern layout container */
.bk-wrapper {
    display: flex;
    justify-content: center;
    padding: 2rem 1rem;
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    color: var(--text-primary, #1e293b);
}

.bk {
    width: 100%;
    max-width: 720px;
}

.bk h1 {
    font-size: 24px;
    font-weight: 600;
    margin-bottom: 1.5rem;
    display: flex;
    align-items: center;
    gap: 12px;
    color: var(--text-dark, #0f172a);
}

/* Modern Card Design */
.bk-card {
    background: var(--card-bg, #ffffff);
    border: 1px solid var(--border-color, #e2e8f0);
    border-radius: 12px;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
    overflow: hidden;
    margin-bottom: 1.5rem;
}

.bk-ch {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 16px 20px;
    border-bottom: 1px solid var(--border-color, #e2e8f0);
    background: var(--surface-bg, #f8fafc);
}

.bk-ci { font-size: 18px; }
.bk-ct {
    font-size: 14px;
    font-weight: 600;
    color: var(--text-muted, #475569);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.bk-body { padding: 24px; }

/* Stats grid */
.bk-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
}

.bk-stat {
    background: var(--surface-bg, #f1f5f9);
    border-radius: 10px;
    padding: 16px;
    border: 1px solid var(--border-color, #e2e8f0);
}

.bk-sl {
    font-size: 12px;
    color: var(--text-muted, #64748b);
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    font-weight: 500;
}

.bk-sv { font-size: 22px; font-weight: 600; color: var(--text-dark, #0f172a); }
.bk-sv.sm { font-size: 15px; padding-top: 4px; }

/* Buttons */
.bk-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 10px 20px;
    font-size: 14px;
    font-weight: 500;
    border-radius: 8px;
    border: 1px solid var(--border-color, #cbd5e1);
    background: var(--card-bg, #fff);
    color: var(--text-primary, #334155);
    cursor: pointer;
    transition: all 0.2s ease;
    text-decoration: none;
}

.bk-btn:hover { background: var(--surface-bg, #f8fafc); border-color: #94a3b8; }
.bk-btn.primary { background: #0f172a; color: #fff; border-color: #0f172a; }
.bk-btn.primary:hover { background: #1e293b; border-color: #1e293b; box-shadow: 0 4px 12px rgba(15, 23, 42, 0.15); }
.bk-btn.danger { background: #ef4444; color: #fff; border-color: #ef4444; }
.bk-btn.danger:hover { background: #dc2626; border-color: #dc2626; box-shadow: 0 4px 12px rgba(239, 68, 68, 0.2); }
.bk-btn:disabled { opacity: 0.5; cursor: not-allowed; box-shadow: none !important; }

/* Upload Area */
.bk-upload {
    display: block;
    border: 2px dashed var(--border-color, #cbd5e1);
    border-radius: 12px;
    padding: 32px 20px;
    text-align: center;
    cursor: pointer;
    background: var(--surface-bg, #f8fafc);
    transition: all 0.2s ease;
}

.bk-upload:hover, .bk-upload.over {
    border-color: #3b82f6;
    background: #eff6ff;
}

.bk-upload input[type=file] { display: none; }
.bk-upl { font-size: 15px; color: var(--text-muted, #64748b); }
.bk-upl strong { color: #3b82f6; font-weight: 600; }
.bk-ufile {
    display: none;
    margin-top: 14px;
    font-size: 14px;
    font-weight: 600;
    color: #0f172a;
    background: #e0f2fe;
    padding: 8px 12px;
    border-radius: 8px;
    border: 1px solid #bae6fd;
}

/* Warnings and Hints */
.bk-warn {
    background: #fffbeb;
    border: 1px solid #fde68a;
    border-radius: 10px;
    padding: 16px;
    font-size: 14px;
    color: #92400e;
    line-height: 1.6;
    margin-bottom: 20px;
    display: flex;
    gap: 10px;
}

.bk-row { display: flex; gap: 16px; align-items: center; flex-wrap: wrap; margin-top: 20px; }
.bk-hint { font-size: 13px; color: var(--text-muted, #64748b); }

/* Table */
.bk-tbl { width: 100%; font-size: 13px; border-collapse: collapse; }
.bk-tbl th { text-align: left; padding: 12px 16px; color: var(--text-muted, #64748b); font-weight: 600; border-bottom: 1px solid var(--border-color, #e2e8f0); background: #f8fafc; }
.bk-tbl td { padding: 12px 16px; border-bottom: 1px solid var(--border-color, #f1f5f9); vertical-align: middle; }
.bk-tbl tr:last-child td { border-bottom: none; }

.bk-badge {
    display: inline-block;
    font-size: 12px;
    font-weight: 600;
    padding: 4px 10px;
    border-radius: 20px;
}
.bk-badge.ex { background: #e0f2fe; color: #0369a1; }
.bk-badge.im { background: #fef3c7; color: #b45309; }

/* Error Detail Panel */
.bk-errs { background: #fef2f2; border: 1px solid #fecaca; border-radius: 12px; overflow: hidden; margin-bottom: 1.5rem; }
.bk-errs-head { padding: 12px 16px; background: #fee2e2; font-size: 14px; font-weight: 600; color: #b91c1c; }
.bk-err-row { padding: 12px 16px; border-top: 1px solid #fecaca; font-size: 13px; }
.bk-err-n { color: #b91c1c; font-weight: 600; margin-right: 8px; }
.bk-err-sql { font-family: 'JetBrains Mono', monospace; background: #fff5f5; padding: 4px 8px; border-radius: 6px; color: #991b1b; word-break: break-all; margin-bottom: 6px; }
.bk-err-msg { color: #dc2626; font-weight: 500; }

/* Modal */
.bk-backdrop {
    display: none;
    position: fixed;
    inset: 0;
    background: rgba(15, 23, 42, 0.6);
    backdrop-filter: blur(4px);
    z-index: 999;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.2s ease;
}
.bk-backdrop.open { display: flex; opacity: 1; }
.bk-modal {
    background: var(--card-bg, #fff);
    border-radius: 16px;
    padding: 32px;
    max-width: 460px;
    width: 90%;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
    transform: translateY(20px);
    transition: transform 0.2s ease;
}
.bk-backdrop.open .bk-modal { transform: translateY(0); }
.bk-modal h2 { font-size: 20px; font-weight: 600; margin-bottom: 12px; color: #0f172a; }
.bk-modal p { font-size: 14px; color: var(--text-muted, #475569); line-height: 1.6; margin-bottom: 20px; }
.bk-cinput {
    width: 100%;
    font-size: 15px;
    padding: 12px 16px;
    border: 1px solid var(--border-color, #cbd5e1);
    border-radius: 10px;
    background: var(--card-bg, #fff);
    color: var(--text-primary, #0f172a);
    margin-bottom: 20px;
    font-family: inherit;
    transition: border-color 0.2s ease;
}
.bk-cinput:focus { outline: none; border-color: #3b82f6; box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1); }
.bk-mfoot { display: flex; gap: 12px; justify-content: flex-end; }
code.inline { background: var(--surface-bg, #f1f5f9); padding: 2px 8px; border-radius: 6px; font-family: monospace; font-weight: 600; color: #0f172a; }
</style>

<div class="bk-wrapper">
    <div class="bk">
        <h1>🗄️ Backup &amp; Restore</h1>

        <div class="bk-card">
            <div class="bk-ch"><span class="bk-ci">⬇️</span><span class="bk-ct">Download Backup</span></div>
            <div class="bk-body">
                <div class="bk-stats">
                    <div class="bk-stat">
                        <div class="bk-sl">DB Size</div>
                        <div class="bk-sv"><?= formatBytes($dbSize) ?></div>
                    </div>
                    <div class="bk-stat">
                        <div class="bk-sl">Tables</div>
                        <div class="bk-sv"><?= $tableCount ?></div>
                    </div>
                    <div class="bk-stat">
                        <div class="bk-sl">Generated</div>
                        <div class="bk-sv sm"><?= date('d M Y, H:i') ?></div>
                    </div>
                </div>
                <form method="POST">
                    <input type="hidden" name="action" value="download_sql">
                    <div class="bk-row">
                        <button type="submit" class="bk-btn primary">⬇️ Download .sql backup</button>
                        <span class="bk-hint">Pure-PHP dump — no mysqldump required.</span>
                    </div>
                </form>
            </div>
        </div>

        <div class="bk-card">
            <div class="bk-ch"><span class="bk-ci">⬆️</span><span class="bk-ct">Restore from Backup</span></div>
            <div class="bk-body">
                <div class="bk-warn">
                    <span>⚠️</span>
                    <div>
                        <strong>Warning:</strong> Restoring will drop and recreate all tables.
                        This is irreversible. Download a fresh backup first before proceeding.
                    </div>
                </div>

                <form method="POST" enctype="multipart/form-data" id="restoreForm">
                    <input type="hidden" name="action" value="restore_db">
                    <input type="hidden" name="confirm_token" value="<?= htmlspecialchars($restoreToken) ?>">

                    <label class="bk-upload" id="uploadArea" for="sqlFile">
                        <input type="file" name="sql_file" id="sqlFile" accept=".sql" onchange="onFileSelected(this)">
                        <div class="bk-upl">
                            <span style="font-size:32px;display:block;margin-bottom:12px">📂</span>
                            <strong>Click to select</strong> or drag &amp; drop a .sql file
                        </div>
                        <div class="bk-ufile" id="selectedFile"></div>
                    </label>

                    <div class="bk-row">
                        <button type="button" class="bk-btn danger" id="restoreBtn" disabled onclick="openModal()">
                            🔄 Restore Database
                        </button>
                        <span class="bk-hint" id="restoreHint">Select a .sql file to enable restore.</span>
                    </div>
                </form>
            </div>
        </div>

        <?php if ($logs): ?>
        <div class="bk-card">
            <div class="bk-ch"><span class="bk-ci">📋</span><span class="bk-ct">Backup Activity</span></div>
            <div class="bk-body" style="padding:0; overflow-x: auto;">
                <table class="bk-tbl">
                    <thead>
                        <tr><th>Action</th><th>Details</th><th>Date</th></tr>
                    </thead>
                    <tbody>
                        <?php foreach ($logs as $log): ?>
                        <tr>
                            <td>
                                <span class="bk-badge <?= $log['action'] === 'EXPORT' ? 'ex' : 'im' ?>">
                                    <?= e($log['action']) ?>
                                </span>
                            </td>
                            <td style="color:var(--text-muted,#475569)"><?= e($log['note'] ?? '—') ?></td>
                            <td style="white-space:nowrap;color:var(--text-muted,#475569)">
                                <?= e(date('d M Y H:i', strtotime($log['created_at']))) ?>
                            </td>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php endif ?>

        <?php if ($restoreErrors): ?>
        <div class="bk-errs">
            <div class="bk-errs-head">❌ <?= count($restoreErrors) ?> statement(s) failed during restore</div>
            <?php foreach ($restoreErrors as $e): ?>
            <div class="bk-err-row">
                <span class="bk-err-n">#<?= $e['n'] ?></span>
                <div class="bk-err-sql"><?= htmlspecialchars($e['sql']) ?>…</div>
                <div class="bk-err-msg"><?= htmlspecialchars($e['err']) ?></div>
            </div>
            <?php endforeach ?>
        </div>
        <?php endif ?>

    </div>
</div>

<div class="bk-backdrop" id="modal">
    <div class="bk-modal">
        <h2>⚠️ Confirm Restore</h2>
        <p>
            You are about to <strong>overwrite the entire database</strong> with<br>
            <strong id="modalFile" style="word-break:break-all; color:#0f172a;">—</strong>.<br><br>
            Type <code class="inline">RESTORE</code> to confirm. This cannot be undone.
        </p>
        <input type="text" class="bk-cinput" id="confirmInput"
               placeholder="Type RESTORE to confirm" oninput="checkConfirm(this)" autocomplete="off">
        <div class="bk-mfoot">
            <button type="button" class="bk-btn" onclick="closeModal()">Cancel</button>
            <button type="button" class="bk-btn danger" id="doRestore" disabled onclick="submitRestore()">🔄 Yes, Restore</button>
        </div>
    </div>
</div>

<script>
function onFileSelected(input) {
    const file = input.files[0] || null;
    const sf   = document.getElementById('selectedFile');
    const btn  = document.getElementById('restoreBtn');
    const hint = document.getElementById('restoreHint');
    
    if (file) {
        sf.textContent = '✅ ' + file.name + ' (' + fmtSize(file.size) + ')';
        sf.style.display = 'inline-block';
        btn.disabled = false;
        hint.textContent = 'Ready — click Restore to proceed.';
    } else {
        sf.style.display = 'none';
        btn.disabled = true;
        hint.textContent = 'Select a .sql file to enable restore.';
    }
}

function fmtSize(b) {
    if (b >= 1048576) return (b/1048576).toFixed(2) + ' MB';
    if (b >= 1024)    return (b/1024).toFixed(1) + ' KB';
    return b + ' B';
}

// Drag & drop logic
const area = document.getElementById('uploadArea');
area.addEventListener('dragover', e => { e.preventDefault(); area.classList.add('over'); });
area.addEventListener('dragleave', () => area.classList.remove('over'));
area.addEventListener('drop', e => {
    e.preventDefault(); 
    area.classList.remove('over');
    
    const f = e.dataTransfer.files[0];
    if (f && f.name.endsWith('.sql')) {
        const fileInput = document.getElementById('sqlFile');
        const dt = new DataTransfer(); 
        dt.items.add(f);
        fileInput.files = dt.files;
        onFileSelected(fileInput);
    }
});

function openModal() {
    const fileInput = document.getElementById('sqlFile');
    
    if (!fileInput.files || !fileInput.files.length) {
        alert("Please select a valid SQL file first.");
        return;
    }
    
    document.getElementById('modalFile').textContent = fileInput.files[0].name;
    document.getElementById('confirmInput').value    = '';
    document.getElementById('doRestore').disabled    = true;
    document.getElementById('modal').classList.add('open');
}

function closeModal() {
    document.getElementById('modal').classList.remove('open');
}

function checkConfirm(input) {
    document.getElementById('doRestore').disabled = (input.value.trim() !== 'RESTORE');
}

function submitRestore() {
    const btn = document.getElementById('doRestore');
    btn.disabled = true;
    btn.textContent = 'Restoring...';
    document.getElementById('restoreForm').submit();
}

document.getElementById('modal').addEventListener('click', e => {
    if (e.target === document.getElementById('modal')) closeModal();
});
</script>

<?php require_once BASE_PATH . '/includes/footer.php'; ?>